var translations_vi = {
  "ten dang nhap": "Tên đăng nhập",
  "mat khau": "Mật khẩu",
  "dang nhap": "Đăng nhập",

  //menu
  "danh sach": "Danh sách",
  "them moi": "Thêm mới",
  'quay lai': "Quay lại",
  'loc du lieu': 'Lọc dữ liệu',
  "bao cao nghiep vu": "Báo cáo nghiệp vụ",
  "trich xuat": "Trích xuất",
  "xu ly tin": "Xử lý tin",
  "danh sach tin den": "Danh sách tin đến",
  "danh sach tin di": "Danh sách tin đi",
  "tinh hinh": "Tình hình",
  "vu viec": "Vụ việc",
  "tuan tra": "Tuần tra",
  "diem nong": "Điểm nóng",
  "danh sach tinh hinh": "Danh sách tình hình",

  //diem nong
  'them moi diem nong': 'Thêm mới điểm nóng',
  'cap nhat thong tin diem nong': 'Cập nhật thông tin điểm nóng',
  'chi tiet thong tin diem nong': 'Chi tiết thông tin điểm nóng',
  'danh sach diem nong': 'Danh sách điểm nóng',
  'don vi': 'Đơn vị',
  'ten diem nong': 'Tên điểm nóng',
  'thoi gian': 'Thời gian',
  'thanh phan dan toc': 'Thành phần dân tộc',
  'chieu dai bien gioi': 'Chiều dài biên giới',
  'so ho': 'Số hộ',
  'so khau': 'Số Khẩu',
  'tinh chat': 'Tính chất',
  'dia diem TNXH': 'Địa điểm tệ nạn xã hội',
  'ghi chu': 'Ghi chú',
  'tu ngay': 'Từ ngày',
  'den ngay': 'Đến ngày',

  //dia ban doi diedoi dien
  'them moi dia ban doi dien': 'Thêm mới địa bàn dối diện',
  'cap nhat thong tin dia ban doi dien': 'Cập nhật thông tin đia bàn đối diện',
  'chi tiet dia ban doi dien': 'Chi tiết đia bàn đối diện',
  'danh sach dia ban doi dien': 'Danh sách đia bàn đối diện',
  'ten dia ban doi dien': 'Tên đia bàn đối diện',
  'ngay cap nhat': 'Ngày cập nhật',
  'thong tin dia ban doi dien': 'Thông tin đia bàn đối diện',
  'tu ngay': 'Từ ngày',
  'den ngay': 'Đến ngày',

  //dia ban quan ly
  'them moi dia ban quan ly': 'Thêm mới địa bàn quản lý',
  'cap nhat thong tin dia ban quan ly': 'Cập nhật thông tin địa bàn quản lý',
  'chi tiet dia ban quan ly': 'Chi tiết địa bàn quản lý',
  'danh sach dia ban quan ly': 'Danh sách địa bàn quản lý',
  'ten dia ban quan ly': 'Tên địa bàn quản lý',
  'ngay cap nhat': 'Ngày cập nhật',
  'thong tin dia ban quan ly': 'Thông tin địa bàn quản lý',
  'tu ngay': 'Từ ngày',
  'den ngay': 'Đến ngày',

  //thong tin tinh
  'danh sach thong tin tinh hinh theo ngay tai tinh': 'Danh sách thông tin tình hình theo ngày Tỉnh',
  'them moi thong tin tinh hinh theo ngay tai tinh': 'Thêm mới thông tin tình hình theo ngày Tỉnh',
  'cap nhat thong tin tinh': 'Cập nhật thông tin Tỉnh',
  'chi tiet thong tin tinh': 'Chi tiết thông tin Tỉnh',

  //thong tin don
  'danh sach thong tin tinh hinh theo ngay tai don': 'Danh sách thông tin tình hình theo ngày tại Đồn',
  'them moi thong tin tinh hinh theo ngay tai don': 'Thêm mới thông tin tình hình theo ngày tại Đồn',
  'ten don vi': 'Tên đơn vị',
  'ngay cap nhat': 'Ngày cập nhật',
  'nguoi cap nhat': 'Người cập nhật',
  'cap nhat thong tin don': 'Cập nhật thông tin Đồn',
  'chi tiet thong tin don': 'Chi tiết thông tin Đồn',
  'tinh hinh chung': 'Tình hình chung',
  'quan so': 'Quân số',
  'truc': 'Trực ban',
  'xnc': 'Xuất nhập cảnh',
  'thi thuc': 'Cấp thị thực',
  'dia ban': 'Địa bàn',
  'phai doan': 'Phái đoàn',
  'thu tin': 'Thư tín',
  'tiep nhan trao tra': 'Tiếp nhận/Trao trả',
  'loai hinh xnc': 'Loại hình xuất nhập cảnh',
  'loai xuat nhap canh': 'loại xuất nhập cảnh',

  //quan so
  'gio cap nhat': 'Giờ cập nhật',
  'tong so': 'Tổng số',
  'co mat': 'Có mặt',
  'vang mat': 'Vắng mặt',
  'vang mat co ly do': 'Vắng mặt có lý do',
  'vang mat khong ly do': 'Vắng mặt không lý do',
  'Tra cuu du lieu quan so': 'Tra cứu dữ liệu quân số',
  'Bao cao tong hop quan so': "Báo cáo tổng hợp quân số",
  'Don vi': 'Đơn vị',
  'Nam': 'Năm',
  'Thang': 'Tháng',
  'Phan tich': 'Phân tích',
  'QUAN SO QUY HOACH': 'QUÂN SỐ QUY HOẠCH',
  'CAN BO QUAN': 'CÁN BỘ QUẢN',
  'QUAN LUC QUAN': 'QUAN LỰC QUẢN',
  'TONG QUAN SO': 'TỔNG QUÂN SỐ',
  'CAN BO QUAN LY': 'CÁN BỘ QUẢN LÝ',
  'QUAN LUC QUAN LY': 'QUÂN LỰC QUẢN LÝ',
  'QUAN SO DANG NGHI CHUAN BI HUU': 'QUÂN SỐ ĐANG NGHỈ CHUẨN BỊ HƯU',
  'QUAN SO OM DAU DAI NGAY': 'QUÂN SỐ ỐM ĐAU DÀI NGÀY',
  'QUAN SO NU': 'QUÂN SỐ NỮ',
  'I. KHOI CHIEN DAU': 'I. KHỐI CHIẾN ĐẤU',
  'II. KHOI KINH TE': 'II. KHỐI KINH TẾ',
  'QUAN SO HIEN CO': 'QUÂN SỐ HIỆN CÓ',
  'TONG SO': 'TỔNG SỐ',



  //xnc
  'so luog nguoi xuat canh': 'Số lượng người xuất cảnh',
  'so luong nguoi nhap canh': 'Số lượng người nhập cảnh',
  'so luong phuong tien xuat canh': 'Số lượng phương tiện xuất cảnh',
  'so luong phuong tien nhap canh': 'Số lượng phương tiện nhập cảnh',
  'so luong nhan vien phuong tien xuat canh': 'Số lượng nhân viên phương tiện xuất cảnh',
  'so luong nhan vien phuong tien nhap canh': 'Số lượng nhân viên phương tiện nhập cảnh',
  'chi tiet luu luong xnc': 'Chi tiết lưu lượng xuất nhập cảnh',
  'them moi chi tiet luu luong xnc': 'Thêm mới chi tiết lưu lượng xuất nhập cảnh',
  'cap nhat chi tiet luu luong xnc': 'Cập nhật chi tiết lưu lượng xuất nhập cảnh',
  'phan loai': 'Phân loại',
  'loai giay to': 'Loại giấy tờ',
  'loai phuong tien': 'Loại phương tiện',
  'ten hang hoa': 'Tên hàng hóa',
  'quoc tich': 'Quốc tịch',
  'so luong': 'Số lượng',
  'don vi tinh': 'Đơn vị tính',

  //Thi Thuc
  'sumVisa': 'Tổng số thị thực đã cấp',
  'freeExchange': 'Cấp đổi miễn phí',
  'toRefuseVisa': 'Từ chối cấp',

  //Phai Doan
  'listDelegation': 'Danh sách các đoàn xuất nhập cảnh trong ngày',
  'addDelegation': 'Thêm mới thông tin phái đoàn xuất nhập cảnh',
  'type': 'Loại hình',
  'leader': 'Trưởng đoàn',
  'number': 'Số người',
  'content-goal': 'Nội dung/mục đích',
  'updateDelegation': 'Cập nhật thông tin phái đoàn xuất nhập cảnh',
  'detailDelegation': 'Chi tiết thông tin phái đoàn xuất nhập cảnh',

  //Thu Tin
  'listLetter': 'Danh sách thư tín gửi nhận trong ngày',
  'addLetter': 'Thêm mới thông tin thư tín ',
  'fromToPlace': 'Nơi gửi/nhận',
  'fromToPerson': 'Người gửi/nhận',
  'summaryContent': 'Nội dung tóm tắt',
  'updateLetter': 'Cập nhật thông tin thư tín',
  'detailLetter': 'Xem chi tiết thông tin thư tín',

  //Tiep nhan/Trao tra
  'listReceive': 'Danh sách các vụ tiếp nhận/trao trả trong ngày',
  'addReceive': 'Thêm mới thông tin tiếp nhận/trao trả',
  'sumPeople': 'Số lượng người',
  'sumVehicle': 'Số lượng phương tiện',
  'receiveContent': 'Nội dung tiếp nhận, trao trả',
  'updateReceive': 'Cập nhật thông tin tiếp nhận/trao trả',
  'detailReceive': 'Xem chi tiết tiếp nhận/trao trả',
  'dateReceive': 'Ngày tiếp nhận, trao trả',

  //vu viec
  'danh sach vu viec': 'Danh sách vụ việc',
  'them moi vu viec': 'Thêm mới vụ việc',
  'cap nhat thong tin vu viec': 'Cập nhật thông tin vụ việc',
  'chi tiet thong tin vu viec': 'Chi tiết thông tin vụ việc',
  'ngay phat hien': 'Ngày phát hiện',
  'ma vu viec': 'Mã vụ việc',
  'ten vu viec': 'Tên vụ việc',
  'don vi phat hien': 'Đơn vị phát hiện',
  'dia diem': 'Địa điểm',
  'kinh do': 'Kinh độ',
  'vi do': 'Vĩ độ',
  'loai doi tuong': 'Loại đối tượng',
  'so luong doi tuong': 'Số lượng đối tượng',
  'nhom vu viec': 'Nhóm vụ việc',
  'phan loai xu ly': 'Phân loại xử lý',
  'hinh thuc xu ly': 'Hình thức xử lý',
  'tuyen': 'Tuyến',
  'ldth': 'LDTH',
  'noi dung vu viec': 'Nội dung vụ việc',
  'xu ly ban dau': 'Xử lý ban đầu',
  'ket qua xu ly': 'Kết quả xử lý',
  'hinh thuc xu phat': 'Hình thức xử phạt',
  'so tien phat': 'Số tiền phạt',
  'gia tri phat mai tang vat': 'Giá trị phát mại tang vật',
  'gia tri tieu huy tang vat': 'Giá trị tiêu hủy tang vật',
  'bien phap khac phuc': 'Biện pháp khắc phục',
  'de xuat kien nghi': 'Đề xuất, kiến nghị',
  'xin y kien chi dao': 'Xin ý kiến chỉ đạo',
  'trang thai vu viec': 'Trạng thái vụ việc',
  'noi dung yeu cau': 'Nội dung yêu cầu',
  'nguoi nhan': 'Người nhận',
  'don vi nhan': 'Đơn vị nhận',
  'noi dung chi dao': 'Nội dung chỉ đạo',
  'doi tuong': 'Đối tượng',
  'phuong tien giay to': 'Phương tiện/Giấy tờ',
  'tang vat': 'Tang vật',

  //vu viec - doi tuong
  'danh sach doi tuong': 'Danh sách đối tượng',
  'danh sach phuong tien bi tich thu': 'Danh sách phương tiện giấy tờ bị tịch thu',
  'danh sach tang vat bi thu giu': 'Danh sách tang vật bị thu giữ',
  'them moi doi tuong tham gia vu viec': 'Thêm mới đối tượng tham gia vụ việc',
  'cap nhat doi tuong tham gia vu viec': 'Cập nhật đối tượng tham gia vụ việc',
  'chi tiet doi tuong tham gia vu viec': 'Chi tiết đối tượng tham gia vụ việc',
  'ho ten': 'Họ và tên',
  'gioi tinh': 'Giới tính',
  'nam sinh': 'Năm sinh',
  'tuoi': 'Tuổi',
  'so giay to': 'Số giấy tờ',
  'dia chi thuong chu': 'Địa chỉ thường trú',
  'mo ta': 'Mô tả',
  'xu ly': 'Xử lý',
  'gia tri': 'Giá trị',

  //vu viec - phuong tien
  'them moi phuong tien trong vu viec': 'Thêm mới phương tiện/giấy tờ trong vụ việc',
  'cap nhat phuong tien trong vu viec': 'Cập nhật phương tiện/giấy tờ trong vụ việc',
  'chi tiet phuong tien trong vu viec': 'Chi tiết phương tiện/giấy tờ trong vụ việc',
  'loai': 'Loại',
  'ngay thu': 'Ngày thu',
  'so ngay thu giu': 'Số ngày thu giữ',
  'ngay tra lai': 'Ngày trả lại',
  'nguoi tra lai': 'Người trả lại',
  'ngay nhan': 'Người nhận',

  //Vu viec - Tang Vat
  'them moi tang vat trong vu viec': 'Thêm mới tang vật trong vụ việc',
  'cap nhat tang vat trong vu viec': 'Cập nhật tang vật trong vụ việc',
  'chi tiet tang vat trong vu viec': 'Chi tiết tang vật trong vụ việc',
  "listExhibit": "Danh sách tang vật bị thu giữ",
  "addExhibit": "Thêm mới tang vật trong vụ việc ",
  "toProcess": "Xử lý",
  'value': 'Giá trị',
  'description': 'Mô tả',
  'updateExhibit': 'Cập nhật tang vật trong vụ việc ',
  'detailExhibit': 'Chi tiết tang vật trong vụ việc ',

  //Tin
  'Danh sach tin den': 'Danh sách tin đến',
  'Don vi gui': 'Đơn vị gửi',
  'Trang thai': 'Trạng thái',
  'Tu ngay': 'Từ ngày',
  'Toi ngay': 'Đến ngày',
  'Ma so': 'Mã số',
  'Noi dung': 'Nội dung',
  'Tim kiem': 'Tìm kiếm',
  'Cap nhat tin den': 'Cập nhật tin đến',
  'Cap nhat y kien chi dao xu ly': 'Cập nhật ý kiến chỉ đạo xử lý',
  'Chuyen xu ly tin den': 'Chuyển xử lý tin đến',
  'Cap nhat y kien xu ly tin den': 'Cập nhật ý kiến xử lý tin đến',
  'Do khan': 'Độ khẩn',
  'Do mat': 'Độ mật',
  'Vu viec': 'Vụ việc',
  'Ngay gui': 'Ngày gửi',
  'Nguoi gui': 'Người gửi',
  'Nguoi ky': 'Người ký',
  'Ban goc scan': 'Bản gốc scan',
  'Don vi nhan': 'Đơn vị nhận',
  'Ngay nhan': 'Ngày nhận',
  'Nguoi nhan': 'Người nhận',
  'Noi dung chi dao': 'Nội dung chỉ đạo',
  'Ngay chi dao': 'Ngày chỉ đạo',
  'Thoi han xu ly': 'Thời hạn xử lý (Ngày)',
  'Noi dung y kien xu ly': 'Nội dung ý kiến xử lý',
  'Nguoi ky y kien xu ly': 'Người ký ý kiến xử lý',
  'Can co y kien xu ly': 'Cần có ý kiến xử lý?',
  'Noi dung xin y kien chi dao': 'Nội dung xin ý kiến chỉ đạo',
  'Cap nhat chi tiet tin di': 'Cập nhật chi tiết tin đi',
  'Tep goc y kien xu ly': 'Tệp gốc ý kiến xử lý',
  'Tep goc': 'Tệp gốc ("Nếu có")',
  'Y kien chi dao': 'Ý kiến chỉ đạo',
  'Ban goc y kien chi dao': 'Bản gốc ý kiến chỉ đạo',

  'Can co y kien chi dao': 'Cần có ý kiến chỉ đạo',
  'Don vi xu ly chinh': 'Đơn vị xử lý chính',
  'Cac don vi phoi hop': 'Các đơn vị phối hợp',
  'Cap nhat tin di': 'Cập nhật tin đi',
  'Danh sach tin di': 'Danh sách tin đi',
  'Chi tiet tin di': 'Chi tiết tin đi',
  'Chi tiet tin den': 'Chi tiết tin đến',
  'Loai tin': 'Loại tin',
  'Noi dung xu ly': 'Nội dung xử lý',
  'Ngay cap nhat xu ly': 'Ngày cập nhật xử lý',
  'Cac don vi phoi hop xu ly': 'Các đơn vị phối hợp xử lý',
  'Ban goc NDXL': 'Bản gốc NDXL',
  'Ban goc NDCĐ': 'Bản gốc NDCĐ',
  'Gui tin di': 'Gửi tin đi',
  'Tin di': 'Tin đi',
  'Tin den': 'Tin đến',
  'Cap nhat': 'Cập nhật',
  'Xac nhan': 'Xác nhận',
  'Bo qua': 'Bỏ qua',
  'Dong': 'Đóng',
  'Chuyen': 'Chuyển',
  'Xoa': 'Xóa',
  'Gui': 'Gửi',
  'Bao cao tinh hinh xu ly tin di/den': 'Báo cáo tình hình xử lý tin đi/đến',
  'Bao cao tinh hinh xu ly tin den': 'Báo cáo tình hình xử lý tin đến',
  'Bao cao tinh hinh xu ly tin di': 'Báo cáo tình hình xử lý tin đi',
  'Xem bao cao': 'Xem báo cáo',
  'Tin co y kien chi dao xu ly': 'Tin có ý kiên chi đạo xử lý',
  'Tin Da chuyen cac don vi': 'Tin đã chuyển các đơn vị',
  'Tong so tin den': 'Tổng số tin đến',
  'Da xin y kien chi dao': 'Đã xin ý kiến chỉ đạo',
  'Da co y kien chi dao': 'Đã có ý kiến chỉ đạo',
  'Da chuyen': 'Đã chuyển',
  'Da xu ly xong': 'Đã xử lý xong',
  'Phong ban/Don vi': 'Phòng ban/Đơn vị',
  'Tong so tin di': 'Tổng số tin đi',
  'Tin den': 'Tin đến',
  'Tong so Tin di': 'Tin đi',
  'Da gui': 'Đã gửi',
  'Da nhan': 'Đã nhận',
  'Chu tri xu ly da phan hoi thong tin': 'Chu trì xử lý đã phản hồi thông tin',
  'Da gui cac don vi lien quan': 'Đã gửi các đơn vị có liên quan',
  'Da ket thuc xu ly': 'Đã kết thúc xử lý',

  // Tuan tra
  'danh sach thong tin tuan tra': 'Danh sách thông tin tuần tra',
  'them moi thong tin tuan tra': 'Thêm mới thông tin tuần tra',
  'cap nhat thong tin tuan tra': 'Cập nhật thông tin tuần tra',
  'chi tiet thong tin tuan tra': 'Chi tiết thông tin tuần tra',
  'loai hinh': 'Loại hình',
  'tuyen tuan tra': 'Tuyến tuần tra',
  'ngay gio tuan tra': 'Ngày giờ tuần tra',
  'don vi phoi hop': 'Đơn vị phối hợp',
  'so nguoi': 'Số người',
  'phuong tien': 'Phương tiện',
  'mo ta tuyen tuan tra': 'Mô tả tuyến tuần tra',
  'ket qua tuan tra': 'Kết quả tuần tra',

  // Doi tuong nghiep vu
  'danh sach doi tuong nghiep vu': 'Danh sách đối tượng nghiệp vụ',
  'them moi thong tin doi tuong nghiep vu': 'Thêm mới thông tin đối tượng nghiệp vụ',
  'cap nhat thong tin doi tuong nghiep vu': 'Cập nhật thông tin đối tượng nghiệp vụ',
  'chi tiet thong tin doi tuong nghiep vu': 'Chi tiết thông tin đối tượng nghiệp vụ',
  'don vi quan ly': 'Đơn vị quản lý',
  'ho ten': 'Họ tên',
  'nam sinh': 'Năm sinh',
  'dan toc': 'Dân tộc',
  'nghe nghiep': 'Nghề nghiệp',
  'thuong tru': 'Thường trú',
  'he loai': 'Hệ loại',
  'danh muc': 'Danh mục',
  'thoi gian dua vao ql': 'Thời gian đưa vào quản lý',
  'ghi chu': 'Ghi chú',

  //báo cáo
  'tong hop bao cao': 'Tổng hợp báo cáo',
  'tao bao cao tong hop': 'Tạo báo cáo tổng hợp',
  'cap nhat bao cao tong hop': 'Cập nhật báo cáo tổng hợp',
  'chi tiet bao cao tong hop': 'Chi tiết báo cáo tổng hợp',
  'loai bao cao': 'Loại báo cáo',
  'don vi bao cao': 'Đơn vị báo cáo',
  'ngay': 'Ngày',
  'thang': 'Tháng',
  'tuan': 'Tuần',
  'nam': 'Năm',
  'so du lieu truoc': 'Số dữ liệu trước',
  'so hoa bao cao': 'Số hóa báo cáo',

  //update quân số
  'danh sach thuc luc quan so theo thang': 'Danh Sách Thực Lực Quân Số Theo Tháng',
  'cap nhat thong tin thuc luc quan so theo thang': ' Cập Nhật Thông Tin Thực Lực Quân Số Theo Tháng',
  'bao cao tong hop du lieu xnc': 'Báo Cáo Tổng Hợp Số Liệu XNC',
  'cap nhat mat khau': "Cập nhật mật khẩu",
  'don vi truc thuoc': 'Đơn vị trực thuộc',
  'quan so quy hoach': 'Quân Số Quy Hoạch',
  'can bo quan li': 'Cán Bộ Quản Lý',
  'quan luc quan li': 'Quân Lực Quản Lý',
  'quan so hien co': 'Quân Số Hiện Có',
  'tong quan so': 'Tổng quân số',
  'quan so dang chuan bi nghi huu': 'Quân số đang nghỉ chuẩn bị hưu',
  'quan so om dau dai ngay': 'Quân số ốm đau dài ngày',
  'quan so nu': "Quân số nữ",
  'Tu thang': "Từ tháng",
  'den thang': "Đến tháng",


  // Số hóa báo cáo
  'du lieu bao cao': 'Dữ liệu báo cáo',
  'du lieu scan': 'Dữ liệu scan từ máy đọc mã vạch',
};



var translationsCrl = {
  stt: 'STT',
  thaoTac: 'Thao tác',
  messageAddSuccess: "Thêm mới thành công!",
  messageAddError: "Thêm mới không thành công!",
  messageUpdateSuccess: "Cập nhật thành công!",
  messageUpdateError: "Cập nhật không thành công!",
  messageDeleteSuccess: "Xóa thành công!",
  messageDeleteError: "Xóa không thành công!",
  messageDeleteConfirm: "Bạn có chắc chắn xóa bản ghi này không?",
  messageDateWarning: "Ngày bắt đầu phải nhỏ hơn ngày kết thúc!",  
  messageConfirmSuccess: "Xác nhận thành công!",
  messageConfirmError: "Xác nhận không thành công!",

  //diem nong
  diemNong: 'điểm nóng',
  ten: 'Tên',
  tenDonVi: 'Tên đơn vị',
  tenThanhPhanDanToc: 'Thành phần dân tộc',
  tinhChat: 'Tính chất',
  diaDiemTnxh: 'Địa điểm tệ nạn xã hội',
  thoiGianCapNhat: 'Thời gian',
  tinhHinh: 'Tình hình',

  //danh sach thong tin don 
  thoigiancapnhat: 'Ngày cập nhật',
  tenNguoiCapNhat: 'Người cập nhật',

  //xnc
  phanloai: 'Phân loại',
  loaihinhxnc: 'Loại hình xuất nhập cảnh',
  quoctich: 'Quốc tịch',

  //Phai Doan
  songuoi: 'Số người',
  truongdoan: 'Trưởng đoàn',
  noidung: 'Nội dung',

  // Thu Tin
  noiguinhan: 'Nơi gửi nhận',
  nguoiguinhan: 'Người gửi nhận',

  //Tiep nhan/Trao tra
  sophuongtien: 'Số phương tiện',

  // vu viec
  ngayphathien: 'Ngày phát hiện',
  mavuviec: 'Mã vụ việc',
  tenvuviec: 'Tên vụ việc',
  donvi: "Đơn vị",
  donviphathien: 'Đơn vị phát hiện',
  diadiem: 'Địa điểm',
  loaidoituong: 'Loại đối tượng',
  nhomvuviec: 'Nhóm vụ việc',
  phanloaixuly: 'Phân loại xử lý',
  ldth: 'LDTH',
  noidungvuviec: 'Nội dung vụ việc',
  hinhthucxuphat: 'Hình thức xử phạt',
  xinykienchidao: 'Xin ý kiến chỉ đạo',

  //vu viec - doi tuong
  hoten: 'Họ tên',
  namsinh: 'Năm sinh',
  gioitinh: 'Giới tính',
  quoctich: 'Quốc tịch',

  //vu viec - doi tuong
  ngaytichthu: 'Ngày tịch thu',

  //vu viec - tag vat
  loai: 'Loại',
  soluong: 'Số lượng',
  donvitinh: 'ĐVT',
  hinhthucxuly: 'Hình thức xử lý',
  giatri: "Giá trị",
  mota: "Mô tả",
  xuly: "Xử lý",

  // tuan tra
  ngaytuantra: 'Ngày tuần tra',
  tuyen: 'Tuyến',
  loaihinh: 'Loại hình',
  mota: 'Mô tả',

  // doi tuong vu viec
  phanloai: 'Phân loại',
  heloai: 'Hệ loại',
  hoten: 'Họ tên',
  namsinh: 'Năm sinh',
  nghenghiep: 'Nghề nghiệp',

  //updatequanso
  nam: ' Năm',
  thang: ' Tháng',
  ngaycapnhat: 'Ngày Cập Nhật',
  thaotac: 'Thao Tác',
  tongqs: ' Tổng quân số',
  cong: 'Cộng',

};
